### ISSUE TITLE
Problem with CSS import

### ISSUE THREAD

**Issue by esrichardd** [Ornaldo-RP-R/React-Time-Picker-Input#1]
When using the library, the console generates this problem:

`error - ./node_modules/react-time-picker-input/dist/components/TimeInput.css`
`Global CSS cannot be imported from within node_modules.`
`Read more: https://nextjs.org/docs/messages/css-npm`
`Location: node_modules/react-time-picker-input/dist/components/TimeInput.js`

It's frustrating since I can't find a solution, apparently it's bad practice to import CSS into dependencies.
How could I fix it? I need to use the library.

**Comment by sufiyank97** [comment]
Any UPdate on this issue?

**Comment by shubham-Noustek** [comment]
I have a very similar problem, if you have found a solution to it, please drop it here, thanks!

**Comment by Ornaldo-RP-R** [comment]
Sorry for late response but have not got notification from this issue
I tried fixing today . I removed css from default import and now users must import by their own . Watch readme how to import styles and update library
